apiVersion: aws.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  namespace: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: correct-aws-cred
      key: credentials