apiVersion: platform.example.com/v1alpha1
kind: XNetwork
metadata:
  name: my-network-2
  namespace: default
spec:
  crossplane:
    compositionRef:
      name: xnetworks-aws
  parameters:
    region: ap-south-1
    cidrBlock: "10.1.0.0/16"
    subnetCidr: "10.1.1.0/24"