apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.aws
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XBucket

  resources:
    - name: s3-bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            region: ap-south-1
          providerConfigRef:
            name: default

      patches:
        # bucket name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: metadata.name

        # region override
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

        # versioning
        - type: FromCompositeFieldPath
          fromFieldPath: spec.versioning
          toFieldPath: spec.forProvider.versioning[0].enabled
          policy:
            fromFieldPath: Optional
