apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/shilucloud/crossplane-agent
    path: single-agent
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true